### ISSUE TITLE
Location of asset source files (JS/CSS)?

### ISSUE THREAD

**Issue by ahukkanen** [karolina-engine/place-to-experiment-frontend#2]
I can find the compiled asset files for the "place to experiment" under `public_html/place-to-experiment` but I'm not able to find the source files for this. Could you clarify where we can find the JavaScript and CSS source files?

**Comment by arnarfjodur** [comment]
Hi @ahukkanen . This is located in the [other repository](https://github.com/karolina-engine/place-to-experiment-api/tree/master/frontend_components).

I can see how it is logical to look for it in the front end repository. For us it was more convenient to have it part of the same repo as the API since the API and the JS which interacts with the API are coupled.

This repository here is very much a concrete implementation of certain website (www.kokeilunpaikka.fi), while the other is a reusable tool. As I mentioned to you in another comment, this is still to be clarified with the stakeholders.

**Comment by ahukkanen** [comment]
OK, thanks! Makes perfect sense and I was actually wondering what that folder was for but did not look further into it.
